;;;; gateway-forward-decls.lisp - Forward declarations for gateway.lisp
;;;;
;;;; This file declares functions that are called in gateway.lisp but
;;;; defined in later-compiled modules. This allows SBCL to compile
;;;; gateway.lisp without fatal errors.

(in-package :lispim-core)

;; Group functions (group.lisp)
(declaim (ftype (function (t t t t t &key) t) create-group))
(declaim (ftype (function (t) t) get-group))
(declaim (ftype (function (t t t) t) update-group))
(declaim (ftype (function (t) t) delete-group))
(declaim (ftype (function (t) t) get-group-members))
(declaim (ftype (function (t t t) t) add-group-member))
(declaim (ftype (function (t t) t) remove-group-member))
(declaim (ftype (function (t t t) t) set-group-admin))
(declaim (ftype (function (t t) t) get-groups-by-user))

;; Favorites functions (favorites.lisp)
(declaim (ftype (function (t t) t) add-favorite))
(declaim (ftype (function (t) t) remove-favorite))
(declaim (ftype (function (t) t) get-favorites))
(declaim (ftype (function (t) t) favorite-exists-p))

;; Call functions (call.lisp)
(declaim (ftype (function (t t t &key) t) create-call))
(declaim (ftype (function (t) t) get-call))
(declaim (ftype (function (t t) t) update-call-status))
(declaim (ftype (function (t t t) t) join-call))
(declaim (ftype (function (t) t) leave-call))
(declaim (ftype (function (t) t) end-call))

;; Poll functions (poll.lisp)
(declaim (ftype (function (t t t t t &key) t) create-poll))
(declaim (ftype (function (t) t) get-poll))
(declaim (ftype (function (t t) t) cast-vote))
(declaim (ftype (function (t) t) close-poll))
(declaim (ftype (function (t) t) get-poll-results))

;; Moment functions (moment.lisp)
(declaim (ftype (function (t t &key) t) create-moment))
(declaim (ftype (function (t) t) get-moment))
(declaim (ftype (function (t t) t) delete-moment))
(declaim (ftype (function (t t) t) like-moment))
(declaim (ftype (function (t t) t) comment-moment))
(declaim (ftype (function (t) t) get-moments-timeline))

;; Contact functions (contact.lisp)
(declaim (ftype (function (t t) t) add-contact))
(declaim (ftype (function (t) t) remove-contact))
(declaim (ftype (function (t) t) get-contacts))
(declaim (ftype (function (t) t) get-contact-requests))
(declaim (ftype (function (t t) t) accept-contact-request))
(declaim (ftype (function (t t) t) reject-contact-request))
(declaim (ftype (function (t t) t) block-user))
(declaim (ftype (function (t) t) get-blocked-users))

;; File transfer functions (file-transfer.lisp)
(declaim (ftype (function (t t t &key) t) create-file-transfer))
(declaim (ftype (function (t) t) get-file-transfer))
(declaim (ftype (function (t t) t) upload-file-chunk))
(declaim (ftype (function (t) t) complete-file-transfer))
(declaim (ftype (function (t) t) cancel-file-transfer))

;; Notification functions (notification.lisp)
(declaim (ftype (function (t t t &key) t) create-notification))
(declaim (ftype (function (t) t) get-notifications))
(declaim (ftype (function (t t) t) mark-notification-read))
(declaim (ftype (function (t) t) delete-notification))
(declaim (ftype (function (t) t) clear-notifications))

;; Webhook functions (webhook.lisp)
(declaim (ftype (function (t t t &key) t) create-webhook))
(declaim (ftype (function (t) t) get-webhook))
(declaim (ftype (function (t t) t) update-webhook))
(declaim (ftype (function (t) t) delete-webhook))
(declaim (ftype (function (t) t) get-webhooks-by-user))
(declaim (ftype (function (t t) t) trigger-webhook))

;; Privacy functions (privacy.lisp)
(declaim (ftype (function (t t) t) set-privacy-setting))
(declaim (ftype (function (t) t) get-privacy-settings))
(declaim (ftype (function (t t) t) add-privacy-exception))
(declaim (ftype (function (t t) t) remove-privacy-exception))

;; Voice message functions (voice-messages.lisp)
(declaim (ftype (function (t t t &key) t) create-voice-message))
(declaim (ftype (function (t) t) get-voice-message))

;; User status functions (user-status.lisp)
(declaim (ftype (function (t t) t) set-user-status))
(declaim (ftype (function (t) t) get-user-status))
(declaim (ftype (function (t) t) get-online-users))

;; Chat folder functions (chat-folders.lisp)
(declaim (ftype (function (t t &key) t) create-chat-folder))
(declaim (ftype (function (t) t) get-chat-folder))
(declaim (ftype (function (t t) t) update-chat-folder))
(declaim (ftype (function (t) t) delete-chat-folder))
(declaim (ftype (function (t) t) get-chat-folders))

;; Group channel functions (group-channels.lisp)
(declaim (ftype (function (t t &key) t) create-group-channel))
(declaim (ftype (function (t) t) get-group-channel))
(declaim (ftype (function (t t) t) update-group-channel))
(declaim (ftype (function (t) t) delete-group-channel))
(declaim (ftype (function (t) t) get-group-channels))

;; Plugin functions (plugin.lisp)
(declaim (ftype (function () t) get-loaded-plugins))
(declaim (ftype (function (t) t) get-plugin-info))
(declaim (ftype (function (t) t) enable-plugin))
(declaim (ftype (function (t) t) disable-plugin))
(declaim (ftype (function (t t &key) t) install-plugin))
(declaim (ftype (function (t) t) uninstall-plugin))

;; Link metadata functions (linkmeta.lisp)
(declaim (ftype (function (t) t) fetch-link-metadata))

;; Panel functions (panel.lisp)
(declaim (ftype (function (t t t &key) t) create-panel))
(declaim (ftype (function (t) t) get-panel))
(declaim (ftype (function (t t) t) update-panel))
(declaim (ftype (function (t) t) delete-panel))
(declaim (ftype (function (t) t) get-panels))

;; OAuth functions (oauth.lisp)
(declaim (ftype (function (t t t t &key) t) create-oauth-app))
(declaim (ftype (function (t) t) get-oauth-app))
(declaim (ftype (function (t t) t) update-oauth-app))
(declaim (ftype (function (t) t) delete-oauth-app))
(declaim (ftype (function (t) t) get-oauth-apps-by-user))
(declaim (ftype (function (t t t) t) authorize-oauth))
(declaim (ftype (function (t t) t) get-oauth-token))
(declaim (ftype (function (t) t) revoke-oauth-token))

;; WebSocket helper functions
(declaim (ftype (function (t) t) encode-ws-frame))
(declaim (ftype (function (t) t) decode-ws-frame))
(declaim (ftype (function (t t t) t) send-ws-message))

;; Redis helper macros
(declaim (special *redis-pool*))

;; Connection accessors are defined in types.lisp via defstruct
;; These are automatically created and should NOT be redeclared here
;; to avoid FTYPE mismatch warnings:
;; - connection-id, connection-user-id, connection-state, etc.
;; - (setf connection-user-id), (setf connection-state), etc.

;; Misc utilities
;; Note: socket-user-id and (setf socket-user-id) are removed - these are
;; struct accessors defined in types.lisp, not forward declarations
(declaim (ftype (function () t) random-session-id))
(declaim (ftype (function (t) t) highlighted-message-p))
(declaim (ftype (function (t) t) add-highlighted-message))
(declaim (ftype (function (t) t) booleanp))
(declaim (ftype (function (t t &optional t) t) make-api-error))

;; Broadcast functions
(declaim (ftype (function (t t &key) t) broadcast-to-group))
(declaim (ftype (function (t t &key) t) broadcast-to-users))

;; Global variables (declared as special)
(declaim (special *current-user-id*))
(declaim (special *log-level*))
(declaim (special *oc-api-key*))
(declaim (special *oc-endpoint*))
(declaim (special *room-roles*))
(declaim (special *snowflake-last-timestamp*))
(declaim (special *sync-anchors-lock*))
(declaim (special *sync-stats-lock*))
(declaim (special *connections*))
(declaim (special *connections-lock*))
(declaim (special *connections-active-gauge*))
(declaim (special *heartbeat-interval*))
(declaim (special *heartbeat-timeout*))
(declaim (special *redis-pool*))
(declaim (special *current-handler*))

;; Additional utility functions
(declaim (ftype (function () t) generate-snowflake))
(declaim (ftype (function () t) generate-token))
(declaim (ftype (function (t) t) get-message-by-id))
(declaim (ftype (function (t) t) get-user-by-id))
(declaim (ftype (function (t) t) create-message))
(declaim (ftype (function (t) t) delete-message))
(declaim (ftype (function (t) t) log-warning))
(declaim (ftype (function (t) t) keywordify))
;; Note: 'random' is a CL built-in - removed to avoid package lock error
(declaim (ftype (function (t t) t) store-session))
(declaim (ftype (function (t) t) get-session))
(declaim (ftype (function (t) t) invalidate-session))
(declaim (ftype (function () t) cleanup-expired-sessions))
(declaim (ftype (function (t) t) save-fcm-token))
(declaim (ftype (function (t) t) remove-fcm-token))
(declaim (ftype (function (t) t) get-user-fcm-tokens))
(declaim (ftype (function (t t) t) push-notification))
(declaim (ftype (function (t t) t) broadcast-to-user))
(declaim (ftype (function (t) t) close-connection))
(declaim (ftype (function (t) t) send-message-to-connection))
(declaim (ftype (function (t t) t) send-notification-to-connection))
(declaim (ftype (function (t) t) send-to-connection))
(declaim (ftype (function (t) t) socket-id))
(declaim (ftype (function (t) t) socket-ip))
(declaim (ftype (function (t) t) socket-token))
(declaim (ftype (function (t) t) connection-host))
(declaim (ftype (function (t) t) connection-id))
(declaim (ftype (function (t) t) connection-port))
(declaim (ftype (function (t) t) connection-state))
(declaim (ftype (function (t) t) connection-user-id))
(declaim (ftype (function (t (integer 0 *)) t) (setf connection-user-id)))
(declaim (ftype (function (t t) t) (setf connection-state)))
(declaim (ftype (function (t) t) (setf socket-user-id)))
(declaim (ftype (function (t) t) bloom-filter-add))
(declaim (ftype (function (t t) t) bloom-filter-contains-p))
(declaim (ftype (function (t) t) redis-sadd))
(declaim (ftype (function (t) t) redis-scard))
(declaim (ftype (function (t t) t) redis-setex))
(declaim (ftype (function (t) t) redis-smembers))
(declaim (ftype (function (t t) t) redis-srem))
(declaim (ftype (function (t t t) t) redis-zadd))
(declaim (ftype (function (t t) t) redis-zrange))
(declaim (ftype (function (t t) t) redis-zrem))
(declaim (ftype (function (t t t) t) regex-replace-all))
(declaim (ftype (function (t t t) t) replace-re-all))
(declaim (ftype (function (t t) t) unix-ms-to-lispim-universal))
(declaim (ftype (function (t) t) user-to-plist))
(declaim (ftype (function () t) with-redis-lock))
(declaim (ftype (function (t) t) decode-tlv-list))
(declaim (ftype (function (t t) t) encode-ws-message))
(declaim (ftype (function (t t) t) is-admin-in-conversation))
(declaim (ftype (function (t) t) multi-level-cache-redis-client))
(declaim (ftype (function (t t) t) push-to-online-user))
(declaim (ftype (function (t t) t) push-to-online-users))
(declaim (ftype (function (t) t) broadcast-message))
(declaim (ftype (function (t t) t) search-contacts))
(declaim (ftype (function (t t) t) read-u64-be))
(declaim (ftype (function (t t) t) read-u16-be))
(declaim (ftype (function (t t t) t) write-u64-be))
(declaim (ftype (function (t t t) t) write-u16-be))
(declaim (ftype (function () t) invalidate-all-user-sessions))
(declaim (ftype (function (t) t) get-group-members))
(declaim (ftype (function (t) t) get-file-metadata))

;; Gateway functions (defined in gateway.lisp)
;; Note: Using (t) for &key functions - SBCL requires proper type specifiers
(declaim (ftype (function (t) t) start-gateway))
(declaim (ftype (function () t) stop-gateway))
(declaim (ftype (function () t) gateway-running-p))
